# .streamlit/secrets.toml
# 이 파일은 절대 GitHub에 올리지 마세요!

[anthropic]
api_key = "sk-ant-여기에_Claude_API_키_입력"

[gcp_service_account]
type = "service_account"
project_id = "여기에_프로젝트_ID"
private_key_id = "여기에_키_ID"
private_key = "여기에_개인키"
client_email = "여기에_서비스_계정_이메일"
client_id = "여기에_클라이언트_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
